### ISSUE TITLE
Please add a licence file

### ISSUE THREAD

**Issue by LandingEllipse** [nbearson/grain#2]
Hi, 

thanks for putting this handy little project on GitHub. To increase its usefulness to people who come across this project in the future, could you please specify a licence? [https://choosealicense.com/](https://choosealicense.com/) is a good place to start.

Many thanks!

**Comment by nbearson** [comment]
Hi, I'm glad that people are still getting use out of this old code!

I've added GPLv3 as the license. If you (or anyone else coming across this) require a different license, feel free to contact me about it.
